### ISSUE TITLE
Add function that blocks until au16regs is updated

### ISSUE THREAD

**Issue by xoviat** [alejoseb/Modbus-STM32-HAL-FreeRTOS#3]
Currently ModbusQuery returns immediately, and the user must check periodically to determine whether au16regs has been updated. It would be nice to have a new function (ModbusQueryBlock) that blocks until `xSemaphoreGive(modH->ModBusSphrHandle); //Release the semaphore` is run.

**Comment by alejoseb** [comment]
Hi, the semaphore of modH is not meant for synchronization, it is actually used as  a mutex to protect the handlers and au16regs when the Modbus or user's tasks are accessing these structures. The library requires some updates to use the correct OS primitive, i.e. mutex rather than a binary semaphore.
 
Besides, I added a notification mechanism, which is meant to block until any of these events occurs: the slave responds correctly, query timeouts, or  the slave's answer cannot be validated (size, CRC, etc.)

Check the updated  F103 project for a working example with newly added notifications.

**Comment by xoviat** [comment]
Thanks.
