### ISSUE TITLE
Ethernet Communication with Lwip TCP /IP 

### ISSUE THREAD

**Issue by anilizgu1** [alejoseb/Modbus-STM32-HAL-FreeRTOS#53]
Hello,

I've added the Modbus TCP library with the ModbusH743TCP example for my own project. My board is stm32h747-disc0. I am trying to see the firstly ethernet communication between board to pc over Ethernet peripheral. Software gets stuck into prvCheckTasksWaitingTermination() but I think it is not related to your Modbus library. When I ping the IP over the cmd window I couldn't be able to communicate with the board yet. To do that, which parts of code do I need to check especially?

Thanks in advance.

**Comment by alejoseb** [comment]
Sorry, I cannot provide support for a particular implementation.
It is expected that the freertos.c is different since that is not part of the library, it is part of an example, or your implementation.
You should first have a TCP connection working  and tested with ping in your board and then try to port the library on top of that.

**Comment by anilizgu1** [comment]
Okay, thank you. I will do the TCP connection working first as you suggest.

**Comment by alejoseb** [comment]
I think you did not initialized the modbus handler in main.c. 
You can see the initialization in this example: 

https://github.com/alejoseb/Modbus-STM32-HAL-FreeRTOS/blob/32eb8bd122530acb003e28bcbf0fd2324154208f/Examples/ModbusF429/Core/Src/main.c#L97

**Comment by anilizgu1** [comment]
Hi, thanks for your time and effort to support.

I am a little bit stuck, according to the ModbusH743TCP example configuration, I've added to my project. When I tried to Master mode with the Slave simulation tool on the pc (PymodSlave), the debug program comes here as below. What could be the reason ? Thanks.

![Ekran görüntüsü 2022-06-03 125839](https://user-images.githubusercontent.com/59607784/171833524-25fedff0-18e8-4b6c-9ab3-d2d0a7379213.png)

**Comment by alejoseb** [comment]
As you can read there, that might happen if you are running out of heap. Check the configuration of your project, including the heap for each FreeRTOS task that you are creating.

**Comment by DmitryWorks** [comment]
Hello, I'm testing your library on NUCLEO-H743ZI2 for Modbus TCP, I checked everything, for example, writing register reading works. I want to go further, for example if 400000 holding register = 1 turn on the built-in LED on the board by analogy with this video https://www.youtube.com/watch?v=-JRI9GmA0dg only for Modbus TCP, but there are problems when I change the configuration of your project in order to use the built-in LED and generate a new code in the MX Cube, everything stops working at the ping level, tell me what could be the matter? I'm using Cube MX 6.3.0 as you created the project. Thank you.
